/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.av_car_auto_center.view;

import com.av_car_auto_center.Controller.HistoricoProprietarioController;
import com.av_car_auto_center.model.HistoricoProprietario;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class MenuHistoricoProprietario extends javax.swing.JFrame {

    /**
     * Creates new form MenuHistoricoProprietario
     */
    public MenuHistoricoProprietario() {
        initComponents();
        
        HistoricoProprietarioController controller =
            new HistoricoProprietarioController();

        carregarTabela(
            controller.listarTodos()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHistorico = new javax.swing.JTable();
        BntMenu = new javax.swing.JButton();
        BntAdd = new javax.swing.JButton();
        BntBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Historico de Proprietario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT_Image_12_de_jun._de_2026_16_08_46_-_Editado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDHistorico", "DataInicio", "DataFim", "Placa", "CPF/CPNJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableHistorico);

        BntMenu.setBackground(new java.awt.Color(223, 223, 223));
        BntMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntMenu.setForeground(new java.awt.Color(0, 0, 0));
        BntMenu.setText("Menu");
        BntMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntMenuActionPerformed(evt);
            }
        });

        BntAdd.setBackground(new java.awt.Color(223, 223, 223));
        BntAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntAdd.setForeground(new java.awt.Color(0, 0, 0));
        BntAdd.setText("Adicionar");
        BntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAddActionPerformed(evt);
            }
        });

        BntBuscar.setBackground(new java.awt.Color(223, 223, 223));
        BntBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BntBuscar.setForeground(new java.awt.Color(0, 0, 0));
        BntBuscar.setText("Buscar");
        BntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BntBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BntAdd)
                        .addGap(18, 18, 18)
                        .addComponent(BntMenu)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntMenuActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntMenuActionPerformed

    private void BntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAddActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHistoricoProprietario().setVisible(true);
            }
        });
        
        this.dispose();
    }//GEN-LAST:event_BntAddActionPerformed

    private void BntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntBuscarActionPerformed
        try {

            String entrada = JOptionPane.showInputDialog(
                    null,
                    "Digite o ID do Histórico:"
            );

            if (entrada == null) {
                return;
            }

            if (entrada.trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Digite um ID!"
                );
                return;
            }

            int id = Integer.parseInt(entrada);

            HistoricoProprietarioController controller =
                    new HistoricoProprietarioController();

            HistoricoProprietario historico =
                    controller.buscarPorID(id);

            if (historico == null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Histórico não encontrado!"
                );
                return;
            }

            List<HistoricoProprietario> lista =
                    new java.util.ArrayList<>();

            lista.add(historico);

            carregarTabela(lista);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Digite um número válido!"
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao buscar histórico: "
                    + e.getMessage()
            );
        }
    }//GEN-LAST:event_BntBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHistoricoProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHistoricoProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHistoricoProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHistoricoProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHistoricoProprietario().setVisible(true);
            }
        });
    }
    
    private void carregarTabela(List<HistoricoProprietario> historicos) {

        DefaultTableModel modelo = new DefaultTableModel();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        modelo.addColumn("IDHistorico");
        modelo.addColumn("DataInicio");
        modelo.addColumn("DataFim");
        modelo.addColumn("Placa");
        modelo.addColumn("CPF/CNPJ");

        for (HistoricoProprietario h : historicos) {

            modelo.addRow(new Object[]{
                h.getID(),
                formato.format(h.getDataInicio()),
                h.getDataFim() != null
                        ? formato.format(h.getDataFim())
                        : "Em posse",
                h.getVeiculo().getPlaca(),
                h.getCliente().getCPF()
            });
        }

        TableHistorico.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAdd;
    private javax.swing.JButton BntBuscar;
    private javax.swing.JButton BntMenu;
    private javax.swing.JTable TableHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
